export default {
  id: 'sorting',
  title: 'Sorting',
  tagline: 'Eighteen ways to put things in order, as bars, lit 3D columns or blocks you can knock over.',
  algorithms: [
    { id: 'bubble', name: 'Bubble sort', summary: 'Repeatedly swap neighbours that are out of order until a full pass makes no swaps.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'cocktail', name: 'Cocktail shaker', summary: 'Bubble sort that sweeps both ways, so small values near the end move quickly too.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'selection', name: 'Selection sort', summary: 'Find the smallest remaining value and put it at the front, one slot at a time.', complexity: { best: 'O(n²)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'insertion', name: 'Insertion sort', summary: 'Grow a sorted prefix by sliding each new value left into place, like sorting cards in your hand.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'gnome', name: 'Gnome sort', summary: 'Walk forward while things are in order; when they are not, swap and step back.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'shell', name: 'Shell sort', summary: 'Insertion sort over shrinking gaps, so far-away values travel in big jumps first.', complexity: { best: 'O(n log n)', avg: 'O(n^1.25)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'comb', name: 'Comb sort', summary: 'Bubble sort with a gap that shrinks by 1.3 each pass, clearing out small values stuck at the end.', complexity: { best: 'O(n log n)', avg: 'O(n²/2^p)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'odd-even', name: 'Odd–even sort', summary: 'Alternate between comparing odd and even neighbour pairs. Every pair in a phase is independent, so it parallelises well.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'cycle', name: 'Cycle sort', summary: 'Count how many values are smaller to find each value’s exact home. Uses the fewest possible writes.', complexity: { best: 'O(n²)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'pancake', name: 'Pancake sort', summary: 'The only move allowed is flipping a prefix, like a spatula under a stack of pancakes.', complexity: { best: 'O(n)', avg: 'O(n²)', worst: 'O(n²)', space: 'O(1)' } },
    { id: 'merge', name: 'Merge sort', summary: 'Split in half, sort each half, then zip the two sorted halves together.', complexity: { best: 'O(n log n)', avg: 'O(n log n)', worst: 'O(n log n)', space: 'O(n)' } },
    { id: 'quick', name: 'Quick sort', summary: 'Pick a pivot, move smaller values to its left and larger to its right, then recurse on both sides.', complexity: { best: 'O(n log n)', avg: 'O(n log n)', worst: 'O(n²)', space: 'O(log n)' } },
    { id: 'heap', name: 'Heap sort', summary: 'Arrange the array as a max-heap, then repeatedly move the root (the maximum) to the end.', complexity: { best: 'O(n log n)', avg: 'O(n log n)', worst: 'O(n log n)', space: 'O(1)' } },
    { id: 'tim', name: 'Tim sort', summary: 'Insertion-sort small runs, then merge runs pairwise. A simplified take on what Python and Java use.', complexity: { best: 'O(n)', avg: 'O(n log n)', worst: 'O(n log n)', space: 'O(n)' } },
    { id: 'counting', name: 'Counting sort', summary: 'Tally how often each value appears, then write the values back in order. No comparisons at all.', complexity: { best: 'O(n + k)', avg: 'O(n + k)', worst: 'O(n + k)', space: 'O(k)' } },
    { id: 'radix', name: 'Radix sort', summary: 'Stable bucketing by the ones digit, then tens, then hundreds.', complexity: { best: 'O(d·n)', avg: 'O(d·n)', worst: 'O(d·n)', space: 'O(n + 10)' } },
    { id: 'bucket', name: 'Bucket sort', summary: 'Scatter values into range buckets, then sort each small bucket.', complexity: { best: 'O(n + k)', avg: 'O(n + k)', worst: 'O(n²)', space: 'O(n + k)' } },
    { id: 'bitonic', name: 'Bitonic sort', summary: 'A sorting network: a fixed pattern of compare-swaps that GPUs can run in parallel.', complexity: { best: 'O(n log² n)', avg: 'O(n log² n)', worst: 'O(n log² n)', space: 'O(1)' } },
  ],
};
